sylius_twig_hooks:
    hooks:
        sylius_admin.base#stylesheets:
            rich_editor_styles:
                template: '@MonsieurBizSyliusRichEditorPlugin/Admin/stylesheets.html.twig'
                priority: 100
                
        sylius_admin.base#javascripts:
            rich_editor_javascripts:
                template: '@MonsieurBizSyliusRichEditorPlugin/Admin/javascripts.html.twig'
                priority: 100

        sylius_shop.base#javascripts:
            rich_editor_javascripts:
                template: '@MonsieurBizSyliusRichEditorPlugin/Shop/javascripts.html.twig'
                priority: 100
        sylius_shop.base#stylesheets:
            rich_editor_styles:
                template: '@MonsieurBizSyliusRichEditorPlugin/Shop/stylesheets.html.twig'
                priority: 100
                
        sylius_admin.common.create:
            rich_editor_content:
                template: '@MonsieurBizSyliusRichEditorPlugin/Admin/app.html.twig'
                priority: 100
                
        sylius_admin.common.update:
            rich_editor_content:
                template: '@MonsieurBizSyliusRichEditorPlugin/Admin/app.html.twig'
                priority: 100
