monsieurbiz_sylius_richeditor:
    upload_directory: "%env(resolve:MONSIEURBIZ_SYLIUS_RICH_EDITOR_UPLOAD_DIR)%"
    image_upload_directory: "%env(resolve:MONSIEURBIZ_SYLIUS_RICH_EDITOR_IMAGE_UPLOAD_DIR)%"
    ui_elements:
        monsieurbiz.html:
            alias: html
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.html.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.html.description'
            icon: tabler:file-type-html
            wireframe: html
            tags: [ default, html ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\HtmlType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/html.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/html.html.twig'
        monsieurbiz.text:
            alias: text
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.text.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.text.description'
            icon: entypo:text
            wireframe: text-paragraph 
            tags: [ default, text ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\TextType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/text.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/text.html.twig'
        monsieurbiz.quote:
            alias: quote
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.quote.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.quote.description'
            icon: tabler:quote-filled
            wireframe: text-quote
            tags: [ default, quote ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\QuoteType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/quote.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/quote.html.twig'
        monsieurbiz.image:
            alias: image
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.image.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.image.description'
            icon: tabler:photo
            wireframe: image
            tags: [ default, image ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\ImageType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/image.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/image.html.twig'
        monsieurbiz.video:
            alias: video
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.video.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.video.description'
            icon: tabler:video
            wireframe: video-default
            tags: [ default, video ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\VideoType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/video.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/video.html.twig'
        monsieurbiz.button:
            alias: button
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.button.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.button.description'
            icon: teenyicons:button-outline
            wireframe: button
            tags: [ default, button ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\ButtonLinkType # ButtonLink because ButtonType make a button field displayed
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/button.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/button.html.twig'
        monsieurbiz.title:
            alias: title
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.title.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.title.description'
            icon: tabler:heading
            wireframe: title
            tags: [ default, title ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\TitleType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/title.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/title.html.twig'
        monsieurbiz.h1:
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.h1.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.h1.description'
            icon: lucide:heading-1
            wireframe: title-h1
            tags: [ default, title, title-h1 ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\TitleType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/h1.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/h1.html.twig'
            enabled: false
        monsieurbiz.h2:
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.h2.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.h2.description'
            icon: lucide:heading-2
            wireframe: title-h2
            tags: [ default, title, title-h2 ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\TitleType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/h2.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/h2.html.twig'
            enabled: false
        monsieurbiz.h3:
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.h3.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.h3.description'
            icon: lucide:heading-3
            wireframe: title-h3
            tags: [ default, title, title-h3 ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\TitleType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/h3.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/h3.html.twig'
            enabled: false
        monsieurbiz.separator:
            alias: separator
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.separator.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.separator.description'
            icon: tabler:minus
            wireframe: divider
            tags: [ default, separator ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\SeparatorType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/separator.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/separator.html.twig'
        monsieurbiz.anchor:
            alias: anchor
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.anchor.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.anchor.description'
            icon: tabler:anchor
            wireframe: anchor
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\AnchorType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/anchor.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/anchor.html.twig'
            tags: [default, anchor]
        monsieurbiz.youtube:
            alias: youtube
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.youtube.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.youtube.description'
            icon: tabler:brand-youtube
            wireframe: video-youtube
            tags: [ default, youtube ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\YoutubeType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/youtube.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/youtube.html.twig'
        monsieurbiz.image_collection:
            alias: image_collection
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.image_collection.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.image_collection.description'
            icon: tabler:library-photo
            wireframe: image-collection
            tags: [ default, image-collection ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\ImageCollectionType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/image_collection.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/image_collection.html.twig'
        monsieurbiz.two_columns:
            alias: two_columns
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.two_columns.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.two_columns.description'
            icon: tabler:columns-2
            wireframe: two-columns
            tags: [ default, layout, two-columns ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\TwoColumnsType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/two_columns.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/two_columns.html.twig'
        monsieurbiz.column:
            alias: column
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.column.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.column.description'
            icon: tabler:columns-2
            wireframe: column
            tags: [ default, layout, column ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\ColumnType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/column.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/column.html.twig'
        monsieurbiz.row:
            alias: row
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.row.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.row.description'
            icon: tabler:layout-rows
            wireframe: row
            tags: [ default, layout, row ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\RowType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/row.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/row.html.twig'
        monsieurbiz.markdown:
            alias: markdown
            title: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.markdown.title'
            description: 'monsieurbiz_richeditor_plugin.ui_element.monsieurbiz.markdown.description'
            icon: tabler:markdown
            wireframe: markdown
            tags: [ default, markdown ]
            classes:
                form: MonsieurBiz\SyliusRichEditorPlugin\Form\Type\UiElement\MarkdownType
            templates:
                admin_render: '@MonsieurBizSyliusRichEditorPlugin/admin/ui_element/markdown.html.twig'
                front_render: '@MonsieurBizSyliusRichEditorPlugin/shop/ui_element/markdown.html.twig'
