name: Makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:

  php:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.2]

    env:
      SYMFONY_ARGS: --no-tls
      COMPOSER_ARGS: --prefer-dist
      DOCKER_INTERACTIVE_ARGS: -t

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          echo "date.timezone=UTC" | sudo tee /etc/php/${{ matrix.php }}/cli/conf.d/timezone.ini
          echo "${{ matrix.php }}" > .php-version

      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo "::add-path::${HOME}/.symfony/bin"

      - uses: actions/cache@v1
        id: cache-composer
        with:
          path: /home/runner/.composer/cache
          key: composer-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/.composer/cache
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - run: make bazinga
